version: '3.1'
services:
    web:
        image: odoo:14.0
        depends_on:
            - db
        ports:
            - '8069:8069'
    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5433:5433'
        volumes:
            - ./app/db:/var/lib/postgresql/data/pgdata
        secrets:
            - postgresql_password

secrets:
    postgresql_password:
        file: odoo_pg_pass